### PR TITLE
Added support for kubernetes-style pod names

### PR DESCRIPTION
**Pull request by cjbarroso**
Support for kubernetes-style objects.

### CODE REVIEW

**Comment by wfxr** [comment]
Hi @cjbarroso  Can you give me an example what kind of link it matches ?

**Comment by cjbarroso** [comment]
Examle: 

```
$ kubectl get pods --namespace flux 
NAME                              READY   STATUS    RESTARTS   AGE

flux-549b4dbd4c-m2mn9             1/1     Running   0          5d21h
flux-memcached-64f7865494-wjr79   1/1     Running   0          5d21h
helm-operator-7bd5dc5c87-2tdd2    1/1     Running   0          5d21h
```

Here the 3 items in the NAME column are selected. This is very useful when using kubernetes command by hand.

**Comment by wfxr** [comment]
This project aims to efficiently open URLs that browser can access from the terminal. 

I don't think it makes much sense to capture pod names. They cannot be used as url for opening in browser as far as I known. But if capture pod names actually help you in some special cases you can just matain your own fork.

Anyway, thanks for your contribution.

**Comment by cjbarroso** [comment]
Thank you! I'm using it every day, so I guess I'll keep maintaining it

**Comment by wfxr** [comment]
@cjbarroso I hava an idea that add an option to let users have the ability to register their custom filter. In this way users can expand according to their own needs without disturbing others.

**Pull request closed without merging**
