### PR TITLE
feat: allow to set fzf options with tmux option @fzf-url-fzf-options

### PR DESCRIPTION
**Pull request by nifr**
Hi @wfxr , first of all THANK YOU so much for this awesome plugin.

I'm using it every day and it really improves my productivity :)

This PR enables passing custom options to `fzf-tmux` using the tmux option `@fzf-url-fzf-options`.
It gracefully retains the original behaviour if the variable is unset.

The tmux option`@fzf-url-fzf-options` is read on invocation of `fzf-url.sh`. 

This allows to set the variable in your `.tmux.conf` or update it on-the-fly as follows:

```
tmux set -g '@fzf-url-fzf-options' \
  '-w 100% -y 100% --no-preview --layout reverse --multi -0 --prompt "url:  " --no-info --pointer ● --color "gutter:-1,pointer:#00ff00"'
```

The resulting tmux popup (tmux `3.2+`) looks like this:

Screenshot 2021-06-01 at 20 42 34

### CODE REVIEW

**Comment by h0adp0re** [comment]
This is great work. Perhaps document `@fzf-url-fzf-options` as well?

**Comment by nifr** [comment]
> This is great work. Perhaps document `@fzf-url-fzf-options` as well?

Done.

**Comment by h0adp0re** [comment]
Awesome, I trust @wfxr will find this satisfactory.

**Comment by nifr** [comment]
Added missing `--no-border --no-preview` fzf options to the `README.md`.

I'll be happy to see this PR get merged after review by @wfxr  👍

**Comment by wfxr** [comment]
@nifr LGTM! Good design and and nice documentation :+1:.

Thanks you for the contribution! Thanks also to @h0adp0re the review!

**Pull request merged**
